### ISSUE TITLE
[BUG] Add backport label PR is failing on branches other than main

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#495]
### What is the bug?

`add_backport_label.yml` on the `1.x` branch is invalid.

> Error: .github#L1
> Invalid type for `on`

Correct syntax is on `main` branch:
```yml
name: Add Backport Label
on:
  pull_request_target:
    branches: main
    types: opened
```
The `1.x` branch is incorrect. It should either match main (probably preferred to avoid future merge conflicts), or not exist at all, so that it gets ignored:
```yml
on:
  branches: main
  pull_request:
    types: opened
```

### How can one reproduce the bug?

1. Create a pull request to the 1.x branch, which happens when a PR is merged on main to generate the backport PR
2. Push to the 1.x branch, which happens when a backport PR is merged

### What is the expected behavior?

The action doesn't run at all.

### Do you have any screenshots?

![Screenshot 2023-02-27 at 3 51 01 PM](https://user-images.githubusercontent.com/9291703/221715606-64f6129f-e516-4eee-beb2-b05be802f1f5.png)
