### ISSUE TITLE
[BUG] NPE and OpenSearch crash on malformed Extensions.yml

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-java#583]
### What is the bug?

`ExtensionsManager`'s `readFromExtensionsYml()` method [includes the following code](https://github.com/opensearch-project/OpenSearch/blob/5f8193021215cd6979fde66474ec8d74d32ac91a/server/src/main/java/org/opensearch/extensions/ExtensionsManager.java#L587-L599):
```java
// Create extension read from yml config
readExtensions.add(
    new Extension(
        extensionMap.get("name").toString(),
        extensionMap.get("uniqueId").toString(),
        extensionMap.get("hostAddress").toString(),
        extensionMap.get("port").toString(),
        extensionMap.get("version").toString(),
        extensionMap.get("opensearchVersion").toString(),
        extensionMap.get("minimumCompatibleVersion").toString(),
        extensionDependencyList
    )
);
```
If an `extensions.yml` does not have the correct field populated, the `.get("fieldname")` returns `null`.  Attempting to execute `toString()` on `null` results in this unhelpful error message, and an OpenSearch crash:
```
» [2023-03-18T19:06:58,989][INFO ][o.o.e.ExtensionsManager  ] [runTask-0] Loading extensions : /Users/danielwiddis/git/OpenSearch/distribution/archives/darwin-tar/build/install/opensearch-3.0.0-SNAPSHOT/extensions
» [2023-03-19T02:06:59.091209Z] [BUILD] Stopping node

=== Standard error of node `node{::runTask-0}` ===
»  uncaught exception in thread [main]
»  java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "java.util.HashMap.get(Object)" is null
»       at org.opensearch.extensions.ExtensionsManager.readFromExtensionsYml(ExtensionsManager.java:601)
```

### How can one reproduce the bug?

Create an `extensions.yml` missing at least one of the required fields.  The one that I have that caused the crash is the old format:
```
extensions:
  - name: hello-world
    uniqueId: ad
    hostName: 'sdk_host'
    hostAddress: '127.0.0.1'
    port: '4532'
    version: '1.0'
    description: Extension for the Opensearch SDK Repo
    opensearchVersion: '3.0.0'
    javaVersion: '14'
    className: ExtensionsRunner
    customFolderName: opensearch-sdk-java
    hasNativeController: false
```
(Yes, I know the format was changed, and I updated it on my other machine.)

### What is the expected behavior?

Extension fails to load and provides a detailed error message in the log on why ("didn't find required field X in extensions.yml").

OpenSearch does not crash.

### Do you have any additional context?

This relates to versioning.
