### ISSUE TITLE
[FEATURE] Abstract out configuration for extension in extensions.yml

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-sdk-java#702]
### Is your feature request related to a problem?
Coming from https://github.com/opensearch-project/OpenSearch/pull/7235#pullrequestreview-1394590217.
Extensions configuration has:
```
extensions:
  - name: hello-world
    uniqueId: opensearch-sdk-java-1
    hostAddress: '127.0.0.1'
    port: '4532'
    version: '1.0'
    opensearchVersion: '3.0.0'
    minimumCompatibleVersion: '3.0.0'
```

Its about time to refactor this config into abstracted types. 

### What solution would you like?
```
extensions:
  - name: hello-world
    - identity:
       uniqueId: opensearch-sdk-java-1
    - transport:
       hostAddress: '127.0.0.1'
       port: '4532'
    - compatibility:
       version: '1.0'
       opensearchVersion: '3.0.0'
       minimumCompatibleVersion: '3.0.0'
```
This will help enable adding new types of configuration without really changing the top level interfaces. 

### What alternatives have you considered?
Leave it as it is today.
